/** @file id.h @brief default ids which could be specialised. */

#ifndef __lib_build_id
#define __lib_build_id

/** type id */
typedef enum {
	ID_DEFAULT_VOID = 1, 
	ID_DEFAULT_FN_VOID,

	ID_DEFAULT_I8,
	ID_DEFAULT_I8_PTR_FUNC,
	ID_DEFAULT_I16,
	ID_DEFAULT_I16_PTR_FUNC,
	ID_DEFAULT_I32,
	ID_DEFAULT_I32_PTR_FUNC,
	ID_DEFAULT_I64,
	ID_DEFAULT_I64_PTR_FUNC,

	ID_DEFAULT_F16,
	ID_DEFAULT_F16_PTR_FUNC,
	ID_DEFAULT_F32,
	ID_DEFAULT_F32_PTR_FUNC,
	ID_DEFAULT_F64,
	ID_DEFAULT_F64_PTR_FUNC,
	ID_DEFAULT_I32V4_PTR_INP,
	ID_DEFAULT_I32V4_PTR_OUT,
	ID_DEFAULT_END
} e_id_default;

#endif
